<a href="https://colab.research.google.com/github/roytravel/machine-learning/blob/master/tensorflow_tutorial_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 라이브러리 임포트

In [1]:
import pandas as pd
import tensorflow as tf

## heart 데이터셋 다운로드

In [2]:
csv_file = tf.keras.utils.get_file("heart.csv", "https://storage.googleapis.com/applied-dl/heart.csv")

16384/13273 [=====================================] - 0s 0us/step


In [20]:
df = pd.read_csv(csv_file)
df.head(10)

age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0
5   56    1   2       120   236  ...      0.8      1   0      normal       0
6   62    0   4       140   268  ...      3.6      3   2      normal       1
7   57    0   4       120   354  ...      0.6      1   0      normal       0
8   63    1   4       130   254  ...      1.4      2   1  reversible       1
9   53    1   4       140   203  ...      3.1      3   0  reversible       0

[10 rows x 14 columns]

In [21]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

## 범주형 데이터를 numerical value로 변환

In [22]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   1       145   233    1  ...      0      2.3      3   0     2       0
1   67    1   4       160   286    0  ...      1      1.5      2   3     3       1
2   67    1   4       120   229    0  ...      1      2.6      2   2     4       0
3   37    1   3       130   250    0  ...      0      3.5      3   0     3       0
4   41    0   2       130   204    0  ...      0      1.4      1   0     3       0

[5 rows x 14 columns]

In [26]:
target = df.pop('target')

# pandas dataframe으로부터 values를 읽기 위해 사용
# tf.data.Dataset을 사용하면 심플하고 고효율 데이터 파이프라인을 만들 수 있음
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

for feat, targ in dataset.take(5):
  print ("Features: {}, Target: {}".format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


In [27]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

## 데이터셋 셔플 및 배치

In [28]:
train_dataset = dataset.shuffle(len(df)).batch(1)

## 모델 생성 및 트레이닝

In [29]:
def get_compiled_model():
  model = tf.keras.Sequential([
                               tf.keras.layers.Dense(10, activation='relu'),
                               tf.keras.layers.Dense(10, activation='relu'),
                               tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss = tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [31]:
model = get_compiled_model()
model.fit(train_dataset, epochs=30)

Epoch 1/30

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

303/303 [==============================] - 0s 1ms/step - loss: 2.8313 - accuracy: 0.6865
Epoch 2/30
303/303 [==============================] - 0s 1ms/step - loss: 0.9574 - accuracy: 0.6898
Epoch 3/30
303/303 [==============================] - 0s 1ms/step - loss: 0.8065 - accuracy: 0.7195
Epoch 4/30
303/303 [==============================] - 0s 1ms/step - loss: 0.7241 - accuracy: 0.7261
Epoch 5/30
303/303 [==============================] - 0s 1ms/step - loss: 0.6442 - accuracy: 0.7525
Epoch 6/

## Alternative to feature columns

In [33]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss = tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

##### tf.data와 함께 사용될 때 pd.Dataframe의 column 구조를 유지하는 방법은 pd.DataFrame을 dict로 변환하고 해당 dict를 slice하는 것임

In [46]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

#print (df.to_dict('list'))

In [47]:
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [48]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3627 - accuracy: 0.8119
Epoch 2/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3621 - accuracy: 0.8119
Epoch 3/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3616 - accuracy: 0.8119
Epoch 4/15
19/19 [==============================] - 0s 1ms/step - loss: 0.3610 - accuracy: 0.8119
Epoch 5/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3605 - accuracy: 0.8119
Epoch 6/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3601 - accuracy: 0.8119
Epoch 7/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3596 - accuracy: 0.8119
Epoch 8/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3591 - accuracy: 0.8119
Epoch 9/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3586 - accuracy: 0.8119
Epoch 10/15
19/19 [==============================] - 0s 2ms/step - loss: 0.3582 - accuracy: 0.8119
Epoch 11/15
19/19 [