# 신경망 학습

### 4.2.1 평균 제곱 오차

In [8]:
import numpy as np

def mean_squared_error(y, t):
    return 0.5 * np.sum((y-t)**2)

In [12]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
mean_squared_error(np.array(y), np.array(t))

0.09750000000000003

In [15]:
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
mean_squared_error(np.array(y), np.array(t))

0.5975

### 교차 엔트로피 오차

In [16]:
def cross_entropy_error(y ,t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [17]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
cross_entropy_error(np.array(y), np.array(t))

0.510825457099338

In [18]:
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
cross_entropy_error(np.array(y), np.array(t))

2.302584092994546

미니 배치 학습

In [19]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist

(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

print (x_train.shape)
print (t_train.shape)

(60000, 784)
(60000, 10)


In [20]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

In [21]:
np.random.choice(60000, 10)

array([16858, 59408, 50790, 17506,  3121, 17641,   977, 42013, 18895,
        5714])

### 4.2.4 (배치용) 교차 엔트로피 오차 구현

In [22]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.szie)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

정답 레이블이 원-핫 인코딩이 아니라 2나 7등의 숫자 레이블로 주어졌을 때의 교차 엔트로피 오차는 다음과 같이 구현 #여기 이해 못함

In [ ]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

## 4.3 수치 미분

### 4.3.1 미분

중심 차분

In [23]:
def numerical_diff(f, x):
    h = 1e-4 # 0.0001
    retirn (f(x+h) - f(x-h)) / (2*h)

## 4.4 기울기

In [26]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)
    
    for idx in range(x.size):
        tmp_val = x[idx]
        
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2) / (2*h)
        x[idx] = tmp_val
        
    return grad

경사 하강법

In [24]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x = x - lr * grad
    return x

Problem : 경사법으로 f(x_0, x_1) = x{_0}^2 + x{_1}^2의 최솟값을 구하라

In [27]:
def function_2(x):
    return x[0]**2 + x[1]**2

init_x = np .array([-3.0, 4.0])
gradient_descent(function_2, init_x = init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

In [63]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
# from common.functions import softmax, cross_entropy_error
# from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [54]:
net = simpleNet()
print (net.W)

[[ 2.17262544  1.4597941   1.08287234]
 [ 0.20319825 -0.16642936  1.43398476]]


In [55]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print (p)

[1.48645369 0.72609003 1.94030969]


In [56]:
np.argmax(p)

2